# Generated by Django 4.1.8 on 2023-04-27 13:32

import defect_generator.defects.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defectmodel",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=600,
                null=True,
                upload_to=defect_generator.defects.utils.weights_file_generate_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=600,
                null=True,
                upload_to=defect_generator.defects.utils.image_file_generate_upload_path,
            ),
        ),
    ]
