# Generated by Django 4.1.8 on 2023-05-08 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0004_inferenceimages_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InferenceImages",
            new_name="InferenceImage",
        ),
    ]
