# Generated by Django 4.1.8 on 2023-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0005_rename_inferenceimages_inferenceimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectmodel",
            name="name",
            field=models.CharField(default="", max_length=127),
            preserve_default=False,
        ),
    ]
