# Generated by Django 4.1.8 on 2023-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0009_image_tuned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="tuned",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
