# Generated by Django 4.1.8 on 2023-05-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0010_alter_image_tuned"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="model",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="defects.defectmodel",
            ),
        ),
    ]
