# Generated by Django 4.1.8 on 2023-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0013_alter_result_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="defecttype",
            name="command",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
