# Generated by Django 4.1.8 on 2023-06-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0015_defecttype_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defecttype",
            name="model",
        ),
        migrations.AddField(
            model_name="defecttype",
            name="defect_model",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="defects.defectmodel",
            ),
        ),
    ]
