# Generated by Django 4.2.2 on 2023-07-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0024_result_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="FineTune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Pending"), ("t", "Tuning"), ("f", "Finished")],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fine Tune",
                "ordering": ("created", "id"),
            },
        ),
        migrations.CreateModel(
            name="FineTuneImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fine_tune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fine_tune_images",
                        to="defects.finetune",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fine_tune_images",
                        to="defects.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fine Tune Image",
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="finetune",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "t")),
                fields=("status",),
                name="unique_tuning_fine_tune",
            ),
        ),
    ]
