# Generated by Django 4.2.2 on 2023-07-19 14:47

import defect_generator.defects.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0025_finetune_finetuneimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=600,
                        null=True,
                        upload_to=defect_generator.defects.utils.weights_file_generate_upload_path,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="defectmodel",
            name="file",
        ),
        migrations.AddField(
            model_name="defecttype",
            name="weight",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="defects.weight",
            ),
        ),
    ]
