# Generated by Django 4.2.2 on 2023-07-27 15:47

import defect_generator.defects.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0032_alter_result_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="defecttype",
            name="icon_image",
            field=models.FileField(
                blank=True,
                max_length=600,
                null=True,
                upload_to=defect_generator.defects.utils.results_file_generate_upload_path,
            ),
        ),
    ]
